### PR TITLE
Created help function, fixed typos in main.cpp

### LINKED ISSUE #3: Make a help function
In side main.Cpp file make a function call to help(). 
Write definition of help() above the int main(). 
Void help()
{
}
This help function should display these following on the console. 

•••••••••••••Welcome to To do List•••••••••••••••

              1. Add a new to do
              2. Show remaining todos
              3. Delete a todo
              4. Complete a todo
              5. Statistics
              6. Exit
                 
••••••••••••••••••••••••••••••••••••••••••••••••••••••••

### PR DESCRIPTION
**Pull request by AmalChandru**
Finished with the requested changes. In case of making the output to be displayed at the center, assumed a console of 80 widths(Can be adjusted if required).

### CODE REVIEW

**Review by Rishikeshrajrxl — CHANGES_REQUESTED** [review]
Well up to marks, but only a few changes required 
- make sure the output is displayed in the center.
- there should some length of margin from the left screen.
- also replace the dot with a full stop sign, for a proper view you can check the screenshot on the 
README.md page  https://github.com/FOSS-Cell-GECPKD/Todo-List

**Comment by anandbaburajan** [comment]
@AmalChandru Thanks for contributing! Quick suggestion: please make sure you put something helpful in the PR description.

@Rishikeshrajrxl thanks for leading this project! What do you think about first setting up a well defined structure for your project? Maybe https://github.com/bsamseth/cpp-project for example?

@alwin48 can you take a look at the PR and suggest your opinions? Also it would be great if you look over the coming PRs in this project, thanks!

**Comment by alwin48** [comment]
I think as @AnandBaburajan suggested, @Rishikeshrajrxl you can first set up a well-defined structure for your program. Like for example, you can create a header file for function prototypes and create a source file for their definitions. And maybe put them in a menu folder instead of defining everything in the main file.

**Comment by Rishikeshrajrxl** [comment]
> I think as @AnandBaburajan suggested, @Rishikeshrajrxl you can first set up a well-defined structure for your program. Like for example, you can create a header file for function prototypes and create a source file for their definitions. And maybe put them in a menu folder instead of defining everything in the main file.

I have added a few more specification
https://github.com/Rishikeshrajrxl/Todo-List#specification

**Comment by anandbaburajan** [comment]
> I have added a few more specification

@Rishikeshrajrxl I checked, that's nice but I would recommend both you and @AmalChandru to first check out https://github.com/bsamseth/cpp-project, understand its structure and terms mentioned there and then refer the file structure for your project. Feel free to let us know if you've any doubts!

**Review by Rishikeshrajrxl — APPROVED** [review]
@AmalChandru  It seems you have a good knowledge of C++.  This is as per the requirement.
Looks good to me.

**Comment by anandbaburajan** [comment]
Here's a video I found recently about a CLI todo app: https://vimeo.com/490621534. It's a homework project of some fellowship, but it would give you an idea on how a modern CLI app looks like. This isn't related to the PR but we request you to please explore more about this topic, try to understand the boilerplate repo we suggested earlier and feel free to let us know if you've doubts! Please check @alwin48's comment earlier too on the structure. We did understand your projects 'specifications' and 'features'. You can check out this https://github.com/krishna0512/todo project for some inspiration.

This is why we asked students to discuss about the project before getting started with coding. Now should this PR be closed and you'll create another PR with the initial structure after discussing right?

**Comment by anandbaburajan** [comment]
@hkaur008 can you take a look? Thanks!

**Comment by Rishikeshrajrxl** [comment]
> Here's a video I found recently about a CLI todo app: https://vimeo.com/490621534. It's a homework project of some fellowship, but it would give you an idea on how a modern CLI app looks like. This isn't related to the PR but we request you to please explore more about this topic, try to understand the boilerplate repo we suggested earlier and feel free to let us know if you've doubts! Please check @alwin48's comment earlier too on the structure. We did understand your projects 'specifications' and 'features'. You can check out this https://github.com/krishna0512/todo project for some inspiration.
> 
> This is why we asked students to discuss about the project before getting started with coding. Now should this PR be closed and you'll create another PR with the initial structure after discussing right?

I am thinking to  change everything and go for this CLI todo app: https://vimeo.com/490621534 on your suggestion. Should I do that. @AnandBaburajan

**Comment by anandbaburajan** [comment]
> I am thinking to change everything and go for this CLI todo app: https://vimeo.com/490621534 on your suggestion. Should I do that. @AnandBaburajan

If you wish, sure! Also please note that the repo I shared is not the project in the video.

**Comment by Rishikeshrajrxl** [comment]
Hey, @AmalChandru I really appreciate your hard work and dedication to the project.
And we deeply regret to you because we have decided to change the structure of the project , and for that, we have to close all the PR and revert all the issues created.

**Comment by hkaur008** [comment]
> @hkaur008 can you take a look? Thanks!

yaa sure  , if pr is not closed

**Pull request closed without merging**
